create table if not exists login_events (
 id bigint generated by default as identity primary key,
 provider text not null,
 provider_id text not null,
 email text,
 name text,
 avatar text,
 logged_in_at timestamptz not null default now()
);
create unique index if not exists login_events_provider_user on login_events(provider,provider_id,logged_in_at);
create table if not exists players (
 id bigint generated by default as identity primary key,
 name text not null,
 description text default '',
 logo text default '',
 score integer not null default 0,
 wins integer not null default 0,
 losses integer not null default 0,
 online boolean not null default false,
 updated_at timestamptz not null default now()
);